-- AlterTable
ALTER TABLE "canvass" ALTER COLUMN "date_requested" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "gas_slip" ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "gas_slip_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "item" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "item_location" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "item_movement" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "item_transaction" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "item_type" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "jo_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "job_order" ALTER COLUMN "date_requested" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "material_equipment_quotation_summary" ALTER COLUMN "meqs_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "mcrt" ALTER COLUMN "mcrt_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "mcrt_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "mct" ALTER COLUMN "mct_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "mct_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "meqs_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "mrv" ALTER COLUMN "date_requested" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "exp_date" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "mrv_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "mst" ALTER COLUMN "mst_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "mst_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "mwo_sequence_tracker" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "osriv" ALTER COLUMN "date_requested" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "exp_date" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "osriv_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "pending" ALTER COLUMN "transaction_date" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "po_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "project" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "purchase_order" ALTER COLUMN "po_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "receiving_report" ALTER COLUMN "rr_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "request_voucher" ALTER COLUMN "date_requested" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "work_order_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "rr_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "rv_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "seriv" ALTER COLUMN "date_requested" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "exp_date" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "seriv_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "spare_parts_request" ALTER COLUMN "date_requested" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "spr_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "station" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "supplier" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "trip_ticket" ALTER COLUMN "end_time" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "actual_start_time" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "actual_end_time" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "trip_ticket_approver" ALTER COLUMN "date_approval" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "unit" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "vehicle" ALTER COLUMN "date_acquired" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "deleted_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "vehicle_maintenance" ALTER COLUMN "service_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "next_service_date" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;
